---
- name: 'Vault PKI | Check Local certificate files'
  register: vault_pki_local_files_raw
  ansible.builtin.stat:
    path: '{{ item }}'
  with_items:
    - '{{ vault_pki_pem_path }}'
    - '{{ vault_pki_key_path }}'
    - '{{ vault_pki_ca_pem_path }}'

- name: 'Vault PKI | Index stat results by path'
  set_fact:
    vault_pki_local_files: >-
      {{ dict(
           vault_pki_local_files_raw.results
           | map(attribute='item')
           | zip(vault_pki_local_files_raw.results | map(attribute='stat'))
      ) }}

- name: 'Vault PKI | Check CA expiration'
  when: vault_pki_local_files[vault_pki_ca_pem_path].exists
  register: vault_pki_ca_x509_info
  failed_when: false
  community.crypto.x509_certificate_info:
    path: '{{ vault_pki_pem_path | mandatory }}'
    valid_at:
      renewal_window: '{{ vault_pki_renew_before }}'

- name: 'Vault PKI | Check certificate expiration'
  when: vault_pki_local_files[vault_pki_pem_path].exists
  register: vault_pki_leaf_x509_info
  failed_when: false
  community.crypto.x509_certificate_info:
    path: '{{ vault_pki_pem_path | mandatory }}'
    valid_at:
      renewal_window: '{{ vault_pki_renew_before }}'

- name: 'Vault PKI | Decide if certificate generation is needed'
  set_fact:
    vault_pki_ca_generation_needed: |
      {{
        vault_pki_ca_x509_info.failed | default(false)
        or not vault_pki_local_files[vault_pki_ca_pem_path].exists
        or not (vault_pki_ca_x509_info.valid_at.renewal_window | default(false))
      }}
    vault_pki_leaf_generation_needed: |
      {{
        vault_pki_leaf_x509_info.failed | default(false)
        or not vault_pki_local_files[vault_pki_pem_path].exists
        or not vault_pki_local_files[vault_pki_key_path].exists
        or not (vault_pki_leaf_x509_info.valid_at.renewal_window | default(false))
      }}
