---
- name: 'Vault PKI | Create role'
  hashicorp.vault.vault_write:
    url: '{{ vault_addr }}'
    token: '{{ vault_token }}'
    ca_cert: '{{ cert_vault_ca_path }}'
    path: '{{ vault_pki_engine }}/roles/{{ cert_role | mandatory }}'
    data:
      issuer_ref: '{{ cert_role_issuer_name | mandatory }}'
      organization: '{{ cert_role_info.organization | mandatory }}'
      ou: '{{ cert_role_info.unit | mandatory }}'
      country: '{{ cert_role_info.country | mandatory }}'
      allowed_domains: '{{ cert_role_allow_domains | mandatory }}'
      allow_subdomains: '{{ cert_role_allow_subdomains }}'
      allow_bare_domains: '{{ cert_role_allow_bare_domain }}'
      allow_any_name: '{{ cert_role_allow_any_name }}'
      max_ttl: '{{ cert_role_max_ttl | mandatory }}'
