---
- block:
  - name: 'Vault PKI | Fetch certificate if exist'
    hashicorp.vault.vault_kv2_get:
      url: '{{ vault_addr }}'
      token: '{{ vault_token }}'
      ca_cert: '{{ cert_vault_ca_path }}'
      engine_mount_point: '{{ cert_vault_kv_engine }}'
      path: '{{ cert_vault_storing_path | mandatory | regex_replace("^/+", "") }}'
    register: response
    failed_when: false
    no_log: true

  - name: 'Vault PKI | Fail if Vault read failed'
    fail:
      msg: 'Call to Vault API not working, verify the certificate in /certs on the host'
    when:
      - response.failed | default(false)
      - (response.msg | default('')) is not search('InvalidPath|not found|404|does not exist')
  rescue:
    - fail:
        msg: 'Call to Vault API not working, verify the certificate in /certs on the host'
- set_fact:
    certificate: '{{ response.secret.certificate }}'
    private_key: '{{ response.secret.private_key }}'
    expired: '{{ (response.secret.expiration_date | default(1745829694) | int) < (ansible_date_time.epoch | int) }}'
  no_log: true
  when: not (response.failed | default(false))

- set_fact:
    cert_existing: '{{ not (response.failed | default(false)) }}'
