---
- name: 'Vault PKI | List existing keys'
  delegate_to: localhost
  register: vault_pki_pki_keys
  community.hashi_vault.vault_list:
    path: 'pki/keys'

- name: 'Vault PKI | Generate a new CA'
  run_once: true
  when: >
    vault_pki_ca_key_name not in
    (vault_pki_pki_keys.data.data.key_info | dict2items | map(attribute='value.key_name'))
  block:
    - name: 'Vault PKI | Generating CSR for Application CA'
      delegate_to: localhost
      register: vault_pki_ca_csr_write
      community.hashi_vault.vault_write:
        path: 'pki/intermediate/generate/{{ vault_pki_ca_type }}'
        data:
          common_name:  '{{ vault_pki_ca_common_name       | mandatory }}'
          key_name:     '{{ vault_pki_ca_key_name          | mandatory }}'
          key_type:     '{{ vault_pki_ca_key_type          | mandatory }}'
          organization: '{{ vault_pki_ca_info.organization | mandatory}}'
          ou:           '{{ vault_pki_ca_info.unit         | mandatory}}'
          country:      '{{ vault_pki_ca_info.country      | mandatory}}'
          ttl:          '{{ vault_pki_ca_ttl }}'

    - name: 'Vault PKI | Signing the certificate'
      delegate_to: localhost
      register: vault_pki_ca_signing_resp
      community.hashi_vault.vault_write:
        path: 'pki/root/sign-intermediate'
        data:
          common_name:  '{{ vault_pki_ca_common_name       | mandatory }}'
          organization: '{{ vault_pki_ca_info.organization | mandatory }}'
          ou:           '{{ vault_pki_ca_info.unit         | mandatory }}'
          country:      '{{ vault_pki_ca_info.country      | mandatory }}'
          ttl:          '{{ vault_pki_ca_ttl }}'
          csr:          '{{ vault_pki_ca_csr_write.data.data.csr }}'

    - name: 'Vault PKI | Install Signed Intermediate CA'
      delegate_to: localhost
      register: vault_pki_ca_import_resp
      community.hashi_vault.vault_write:
        path: 'pki/intermediate/set-signed'
        data:
          certificate: "{{ vault_pki_ca_signing_resp.data.data.certificate }}"

    - name: 'Vault PKI | Set name of intermediate issuer'
      delegate_to: localhost
      community.hashi_vault.vault_write:
        path: "pki/issuer/{{ vault_pki_ca_import_resp.data.data.imported_issuers[0] }}"
        data:
          issuer_name:  '{{ vault_pki_ca_issuer_name | mandatory }}'

- name: 'Vault PKI | Read intermediate CA PEM'
  delegate_to: localhost
  register: vault_pki_ca_key_read
  ignore_errors: true
  community.hashi_vault.vault_read:
    path: 'pki/issuer/{{ vault_pki_ca_issuer_name | mandatory }}'

- name: 'Vault PKI | Create certificates directory'
  ansible.builtin.file:
    dest:  '{{ vault_pki_ca_pem_path | dirname }}'
    owner: '{{ vault_pki_user }}'
    group: '{{ vault_pki_group }}'
    state: 'directory'
    mode:  '0o755'

- name: 'Vault PKI | Write CA certificate PEM'
  ansible.builtin.copy:
    content: '{{ vault_pki_ca_key_read.data.data.certificate | mandatory }}'
    dest:    '{{ vault_pki_ca_pem_path | mandatory }}'
    owner:   '{{ vault_pki_user }}'
    group:   '{{ vault_pki_group }}'
    mode:    '{{ vault_pki_pem_mode }}'
