---
- name: 'Vault PKI | Create or update role'
  delegate_to: localhost
  community.hashi_vault.vault_write:
    path: 'pki/roles/{{ cert_role_name | mandatory }}'
    data:
      issuer_ref:         '{{ cert_role_issuer_name       | mandatory }}'
      organization:       '{{ cert_role_info.organization | mandatory }}'
      ou:                 '{{ cert_role_info.unit         | mandatory }}'
      country:            '{{ cert_role_info.country      | mandatory }}'
      max_ttl:            '{{ cert_role_max_ttl           | mandatory }}'
      allowed_domains:    '{{ cert_role_allow_domains     | mandatory }}'
      allow_subdomains:   '{{ cert_role_allow_subdomains }}'
      allow_bare_domains: '{{ cert_role_allow_bare_domain }}'
      allow_any_name:     '{{ cert_role_allow_any_name }}'

- name: 'Vault PKI | Generate certificate'
  delegate_to: localhost
  register: cert_new_raw
  no_log: true
  community.hashi_vault.vault_pki_generate_certificate:
    common_name: '{{ cert_common_name | mandatory }}'
    role_name:   '{{ cert_role_name   | mandatory }}'
    ip_sans:     '{{ cert_ip_sans     | default([]) }}'
    alt_names:   '{{ cert_domain_sans | default([]) }}'

- name: 'Vault PKI | Write certificate PEM'
  ansible.builtin.copy:
    content: '{{ cert_new_raw.data.data.certificate | mandatory }}'
    dest:    '{{ cert_pem_path | mandatory }}'
    owner:   '{{ cert_user }}'
    group:   '{{ cert_group }}'
    mode:    '{{ cert_pem_mode }}'

- name: 'Vault PKI | Write certificate key'
  no_log: true
  ansible.builtin.copy:
    content: '{{ cert_new_raw.data.data.private_key | mandatory }}'
    dest:    '{{ cert_key_path | mandatory }}'
    owner:   '{{ cert_user }}'
    group:   '{{ cert_group }}'
    mode:    '{{ cert_key_mode }}'
