---
- name: 'Vault PKI | Generating CSR for Application CA'
  hashicorp.vault.vault_write:
    url: '{{ vault_addr }}'
    token: '{{ vault_token }}'
    ca_cert: '{{ cert_vault_ca_path }}'
    path: '{{ vault_pki_engine }}/intermediate/generate/exported'
    data:
      common_name: '{{ cert_common_name | mandatory }}'
      issuer_name: '{{ cert_ca_issuer_name | mandatory }}'
      key_name: '{{ cert_ca_issuer_name | mandatory }}'
      organization: '{{ cert_info.organization }}'
      ou: '{{ cert_info.unit }}'
      country: '{{ cert_info.country }}'
      ttl: '{{ cert_ca_ttl }}'
  register: response_csr
  no_log: true

- name: 'Vault PKI | Signing the certificate'
  hashicorp.vault.vault_write:
    url: '{{ vault_addr }}'
    token: '{{ vault_token }}'
    ca_cert: '{{ cert_vault_ca_path }}'
    path: 'pki/root/sign-intermediate'
    data:
      common_name: '{{ cert_common_name | mandatory }}'
      organization: '{{ cert_info.organization }}'
      ou: '{{ cert_info.unit }}'
      country: '{{ cert_info.country }}'
      ttl: '{{ cert_ca_ttl }}'
      csr: '{{ response_csr.data.data.csr }}'
  register: response_signing
  no_log: true

- name: 'Vault PKI | Loading the Application CA'
  hashicorp.vault.vault_write:
    url: '{{ vault_addr }}'
    token: '{{ vault_token }}'
    ca_cert: '{{ cert_vault_ca_path }}'
    path: '{{ vault_pki_engine }}/intermediate/set-signed'
    data:
      certificate: '{{ response_signing.data.data.certificate }}'

- set_fact:
    certificate: '{{ response_signing.data.data.certificate }}'
    private_key: '{{ response_csr.data.data.private_key }}'
  no_log: true
