---
- name: 'Vault PKI | Generating certificate'
  hashicorp.vault.vault_pki_generate_certificate:
    url: '{{ vault_addr }}'
    token: '{{ vault_token }}'
    ca_cert: '{{ cert_vault_ca_path }}'
    engine_mount_point: '{{ vault_pki_engine }}'
    role_name: '{{ cert_role | mandatory }}'
    common_name: '{{ cert_common_name | mandatory }}'
    ip_sans: '{{ cert_ip_sans if cert_ip_sans is sequence and cert_ip_sans is not string else ([cert_ip_sans] if cert_ip_sans else []) }}'
    alt_names: '{{ cert_domain_sans if cert_domain_sans is sequence and cert_domain_sans is not string else ([cert_domain_sans] if cert_domain_sans else []) }}'
  register: new_certificate
  no_log: true

- set_fact:
    certificate: '{{ new_certificate.data.data.certificate }}'
    private_key: '{{ new_certificate.data.data.private_key }}'
  no_log: true
