---
- name: 'Vault PKI | Save the certificate and the private key in Vault'
  hashicorp.vault.vault_kv2_write:
    url: '{{ vault_addr }}'
    token: '{{ vault_token }}'
    ca_cert: '{{ cert_vault_ca_path }}'
    engine_mount_point: '{{ cert_vault_kv_engine }}'
    path: '{{ cert_vault_storing_path | mandatory | regex_replace("^/+", "") }}'
    data:
      certificate: '{{ certificate }}'
      private_key: '{{ private_key }}'
      expiration_date: '{{ ansible_date_time.epoch }}'
  no_log: true
