---
- name: 'Vault PKI | Write the certificate'
  ansible.builtin.copy:
    content: '{{ certificate }}'
    dest: '{{ cert_certificate_path }}'
    owner: '{{ cert_user }}'
    group: '{{ cert_group }}'
    mode: '{{ cert_certificate_mode }}'
  when: certificate | length > 0

- name: 'Vault PKI | Write the private_key'
  ansible.builtin.copy:
    content: '{{ private_key }}'
    dest: '{{ cert_private_key_path }}'
    owner: '{{ cert_user }}'
    group: '{{ cert_group }}'
    mode: '{{ cert_private_key_mode }}'
  when: private_key | length > 0
  no_log: true
