---
## Common Options
vault_pki_common_name: 'example.org'
vault_pki_issuer_name: '{{ vault_pki_common_name }} Issuer'
vault_pki_store_path: '/certs'
vault_pki_pem_path: '{{ vault_pki_store_path }}/{{ vault_pki_common_name }}.pem'
vault_pki_key_path: '{{ vault_pki_store_path }}/{{ vault_pki_common_name }}.key'
vault_pki_renew_before: '+30d'

## Info
vault_pki_info:
  organization: 'IFT Studio Pte Ltd'
  unit:         'Infra'
  country:      'SG'

## SANS
vault_pki_ip_sans: []
vault_pki_domain_sans: []

## Certificate Authority
vault_pki_ca_common_name: '{{ vault_pki_common_name }} CA'
vault_pki_ca_key_name:    '{{ vault_pki_ca_common_name | lower | replace(" ", "-") }}'
vault_pki_ca_pem_path:    '{{ vault_pki_store_path }}/{{ vault_pki_ca_key_name }}.pem'
vault_pki_ca_info:        '{{ vault_pki_info }}'
vault_pki_ca_issuer_name: '{{ vault_pki_ca_key_name | lower | replace(" ", "-") }}'
vault_pki_ca_key_type: 'rsa' # ec, ed25519
vault_pki_ca_ttl: '1825d'
vault_pki_ca_type: 'internal' # 'exported'

## PKI Role
vault_pki_role_name:              '{{ vault_pki_common_name | lower | replace(" ", "-") }}-role'
vault_pki_role_info:              '{{ vault_pki_info }}'
vault_pki_role_issuer_name:       '{{ vault_pki_ca_issuer_name }}'
vault_pki_role_allow_domains:     '{{ [vault_pki_common_name] + vault_pki_ip_sans + vault_pki_domain_sans }}'
vault_pki_role_allow_bare_domain: true
vault_pki_role_allow_subdomains:  true
vault_pki_role_allow_any_name:    true
vault_pki_role_max_ttl:           '365d'

## Permissions
vault_pki_user: 'root'
vault_pki_group: 'root'
vault_pki_pem_mode: '0644'
vault_pki_key_mode: '0600'

## Auth
vault_pki_vault_module_defaults:
  url:                   '{{ lookup("ansible.builtin.env", "VAULT_ADDR") }}'
  token:                 '{{ lookup("ansible.builtin.env", "VAULT_TOKEN") }}'
  ca_cert:               '{{ lookup("ansible.builtin.env", "VAULT_CACERT") }}'
  cert_auth_public_key:  '{{ lookup("ansible.builtin.env", "VAULT_CLIENT_CERT") }}'
  cert_auth_private_key: '{{ lookup("ansible.builtin.env", "VAULT_CLIENT_KEY") }}'
